# Generated by Django 4.2.21 on 2025-12-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_order_id'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiscount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userdiscount',
            name='user',
        ),
        migrations.AddField(
            model_name='userdiscount',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='booking.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('nominal', 'Nominal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='discount_value',
            field=models.IntegerField(),
        ),
    ]
