# Generated by Django 4.2.21 on 2025-11-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('paid', 'Sudah Dibayar'), ('pending', 'Menunggu Konfirmasi')], default='unpaid', max_length=20),
        ),
    ]
