# Generated by Django 4.2.21 on 2025-11-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
