# Generated by Django 4.2.21 on 2025-06-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_approved_booking_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.CharField(choices=[('approved', 'Approverd'), ('not approved', 'Not Approved')], default='not approved', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
