# Generated by Django 4.2.21 on 2025-06-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_approved_alter_booking_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('not approved', 'Not Approved')], default='not approved', max_length=30),
        ),
    ]
