# Generated by Django 6.0 on 2025-12-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_user_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=255)),
                ('predicted_class', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerCluster',
        ),
    ]
