# Generated by Django 4.2.21 on 2025-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_testimonial_alter_photo_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
