# Generated by Django 6.0 on 2025-12-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_testimonial_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Work',
        ),
    ]