# Generated by Django 6.0 on 2025-12-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20251222_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='portfolio.photographer'),
        ),
    ]
